### ISSUE TITLE
Widget not loading correctly

### ISSUE THREAD

**Issue by LeviiiCraft2** [JFK-05/scriptable-untis#10]
Hello, so first of all, thank you for this cool project. I was about to program something similar when I stumbled across this script. Unfortunately, I still have a small problem. Everything works wonderfully, but the widget doesn't seem to load completely. Do you have any idea what the problem could be? I have attached a picture of the widget as it looks at the moment.
Best regards,
LeviiiCraft

![Image](https://github.com/user-attachments/assets/712a4ea7-c2ad-4214-988a-8055c9f0f487)

**Comment by LeviiiCraft2** [comment]
Nevermind, I fixed it, the problem was IOS26 with the transparent theme.

**Comment by kaiser-jan** [comment]
Happy to hear you were able to resolve this by yourself! I’m greatful this project still finds some use :)
I created a new issue (#11) as this problem persists (for everyone who wants to use the clear homescreen) and I am open to contributions.
